import { COLORS } from "@/constants/theme";
import { StyleSheet, Dimensions } from "react-native";

const scanStyles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: COLORS.background,
    },
    buttonRow: {
      flexDirection: 'column',
      alignItems: 'center',
      width: '100%',
    },
    header: {
      height: 60,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 15,
      borderBottomWidth: 1,
      borderBottomColor: COLORS.surface,
      position: 'relative',
      justifyContent: 'center',
    },
    headerButton: {
      width: 60,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitleWrapper: {
      position: 'absolute',
      left: 0,
      right: 0,
      alignItems: 'center',
      justifyContent: 'center',
      height: '100%',
      pointerEvents: 'none',
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: COLORS.white,
      textAlign: 'center',
      width: '100%',
    },
    headerTitleAloneWrapper: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitleAlone: {
      fontSize: 18,
      fontWeight: '600',
      color: COLORS.white,
      textAlign: 'center',
    },
    headerTitleSide: {
      flex: 1,
      fontSize: 18,
      fontWeight: '600',
      color: COLORS.white,
      textAlign: 'left',
    },
    scanButton: {
      width: 90,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: COLORS.primary,
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: 8,
      marginLeft: 10,
    },
    scanButtonText: {
      color: COLORS.white,
      fontWeight: 'bold',
    },
    content: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    emptyStateContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      width: '100%',
    },
    settingsButton: {
      marginHorizontal: 10,
      marginTop: 26,
      position: 'absolute',
      right: 15,
    },
    selectButton: {
      justifyContent: 'center',
      alignItems: 'center',
      padding: 24,
      borderWidth: 2,
      borderColor: COLORS.surface,
      borderStyle: 'dashed',
      borderRadius: 12,
      width: '90%',
      backgroundColor: COLORS.surfaceLight,
      marginBottom: 16,
    },
    selectText: {
      marginTop: 15,
      fontSize: 18,
      fontWeight: '500',
      color: COLORS.primary,
    },
    instructionText: {
      textAlign: 'center',
      color: COLORS.grey,
      paddingHorizontal: 20,
      fontSize: 14,
    },
    previewContainer: {
      width: '100%',
      height: '90%',
      alignItems: 'center',
      backgroundColor: COLORS.surfaceLight,
      borderRadius: 16,
      overflow: 'hidden',
      padding: 10,
    },
    imagePreview: {
      width: '100%',
      height: '90%',
      borderRadius: 8,
    },
    pdfView: {
      flex: 1,
      width: '100%',
      height: '90%',
    },
    fileName: {
      marginTop: 10,
      fontSize: 16,
      fontWeight: '500',
      color: COLORS.white,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    loadingText: {
      marginTop: 16,
      fontSize: 16,
      color: COLORS.primary,
    },
    pdfPlaceholder: {
      flex: 1,
      width: '100%',
      height: '90%',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: COLORS.surfaceLight,
      borderRadius: 8,
    },
    pdfText: {
      marginTop: 20,
      fontSize: 18,
      fontWeight: 'bold',
      color: COLORS.white,
    },
    pdfSubtext: {
      marginTop: 10,
      fontSize: 14,
      color: COLORS.grey,
    },
    viewPdfButton: {
      marginTop: 20,
      backgroundColor: COLORS.primary,
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 8,
    },
    viewPdfButtonText: {
      color: COLORS.white,
      fontWeight: '600',
    },
    dropdownContainer: {
        marginHorizontal: 20,
        marginTop: 16,
        marginRight: 60,
        position: 'sticky',
      },
      dropdownButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.white,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: COLORS.primary,
        padding: 12,
        justifyContent: 'space-between',
      },
      dropdownButtonText: {
        color: COLORS.primary,
        fontWeight: 'bold',
        fontSize: 16,
      },
      dropdownMenu: {
        position: 'absolute',
        top: 50,
        left: 0,
        right: 0,
        backgroundColor: COLORS.white,
        borderRadius: 8,
        elevation: 5,
        zIndex: 10,
        paddingVertical: 4,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
      },
      dropdownItem: {
        padding: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
      },
      dropdownItemText: {
        color: COLORS.primary,
        fontWeight: 'bold',
        fontSize: 16,
      },
  })

export default scanStyles;
